### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by AlexMokin** [elizabeth-zag/cat-telegram-desktop#1]
1) When the I reduce client width number overlaps with the text. See image below
2) add differnet types of messages - at least 3 types (audio, video, image, file etc)

![image](https://user-images.githubusercontent.com/7272208/88206033-51367a80-cc56-11ea-9591-0d3857e774e9.png)

**Comment by ilya4321** [comment]
Thanks, quite good in terms of attention to details, but yeah... it looks like needed to fix issues from Alex still

**Comment by AlexMokin** [comment]
accepted
